# Generated by Django 5.0.6 on 2024-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='word.categoria'),
        ),
    ]
