# Generated by Django 5.0.6 on 2024-12-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_remove_proyecto_categoria_proyecto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word.categoria'),
        ),
    ]
