# Generated by Django 5.0.6 on 2024-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_remove_proyecto_categoria_proyecto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(blank=True, choices=[(10, '10 Q'), (50, '50 Q'), (100, '100 Q')], decimal_places=2, max_digits=10, null=True)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_receipt', models.FileField(upload_to='boletas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
